import type * as d3 from "d3-selection";

export function drawWatermark(
  svg: d3.Selection<SVGSVGElement, unknown, null, undefined>,
  width: number,
  height: number,
  theme: "light" | "dark",
): void {
  const color = theme === "dark" ? "#484f58" : "#8b949e";
  svg
    .append("text")
    .attr("x", width - 10)
    .attr("y", height - 10)
    .attr("text-anchor", "end")
    .attr("font-size", "11px")
    .attr("fill", color)
    .text("Generated by star-history-cli");
}
